version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    command: bundle exec sidekiq -r ./sidekiq_initializer.rb
    volumes:
      - .:/labs
    depends_on:
      - "redis"
      - "db"
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts/create.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: bash -c "sleep 10 && bundle exec ruby server.rb -o 0.0.0.0"
    volumes:
      - .:/labs
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
